// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonOne: string;
  buttonThree: string;
  buttonTwo: string;
  buttoncolor: string;
  left: string;
  right: string;
  root: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
